### ISSUE TITLE
Can't connect to docker engine

### ISSUE THREAD

**Issue by richward1** [kpostekk/homebridge-docker#1]
**Describe The Bug:**
Can't connect to the docker engine.
I've enabled the api, and can send `GET` and `POST` commands to it from postman from a remote machine.

See the following error:
`[4/16/2021, 12:52:06 PM] [Docker] Error: connect EHOSTUNREACH 192.168.2.100:2375`

**To Reproduce:**
Just installed a fresh copy of the plugin, and added the host and port.

**Expected behavior:**
Successful startup

**Logs:**
As above.

**Plugin Config:**

```json
{
    "host": "http://192.168.2.100",
    "port": 2375,
    "secureDelayTimeout": 0,
    "platform": "Docker"
}
```

**Environment:**

* **Plugin Version**:  v2021.5.1
* **Homebridge Version**:  1.3.4
* **Node.js Version**:  14.16.1
* **NPM Version**:  6.14.12
* **Operating System**:  Unraid (Slackware)

**Comment by richward1** [comment]
I'm an idiot.
It's taken me most of the day to realise that my docker config was preventing inter-container communication.
It's working now! :)

**Comment by kpostekk** [comment]
> I'm an idiot.

Everyone makes mistakes, don't worry hah
